### ISSUE TITLE
Login impossible

### ISSUE THREAD

**Issue by MLimone** [Velobook/Application-Mobile-Web#1]
Lorsque je vais sur la page de connexion et entre mes identifiants et clique sur Connexion, rien ne se passe des requêtes sont faites vers _blazor mais je vois pas de requête de login...

**Comment by Velobook** [comment]
Version mise à jour aujourd'hui . Sur URL test.

**Comment by MLimone** [comment]
ça ne fonctionne pas mieux, j'ai eu le spinner la première fois, puis il a disparu et rien ne s'est passé...

Et maintenant lorsque j'essai, le spinner ne s'affiche même pas, rien ne bouge, il y a 3 requêtes

![image](https://user-images.githubusercontent.com/63158602/147966616-ca6b9de5-5e88-4507-933a-0363df74c6ab.png)

**Comment by Velobook** [comment]
L'authentification fait appel à deux API, une spécifique à l'Appli Mobile qui sert de passerelle appelant ensuite soit une DNN API  qui a accès à la base de données SQL qui contient toutes les informations permettant de valider un utilisateur et ses rôles, l'autre permettant l'accès sécurisé aux données coureur stockées dans base de données Mongo dB sur un autre serveur.
Une mise à jour de l'API DNN a résolu et accéléré l'authentification
La version actuelle fonctionne donc maintenant.
